/*  Reid Harry
    1/26/2020
    Please see: https://www.purplemath.com/modules/nextnumb3.htm

    Write a program that takes two seeds (referred to as a_1 and a_2 in the above reference)
    and outputs the first 10 elements (each on their own line) in the sequence generated by
    the process described above. 
*/  

#include<iostream>
using std::cin; using std::cout; using std::endl;

int main(){
    // get two seed values
    int a1, a2;
    cin >> a1 >> a2;

    // output first two values of the series
    cout << a1 << endl << a2 << endl;

    // finds the next 8 values in the series
    int a1temp; // hold the value of a1 temporarily for calculation purposes
    for(int i = 0; i < 8; i++){
        cout << (a1+a2) << endl;
        a1temp = a1;
        a1 = a2;
        a2 = a1temp + a2;
    }
}